### ISSUE TITLE
script failed

### ISSUE THREAD

**Issue by greddost** [bartvbl/itslearning-dumper#7]
Script fails at startup:
`Sending login data
Autodetecting access to HIST
It does not appear you have access to the It's Learning site of HIST
Skipping to the next one.
Autodetecting access to NTNU
Access detected successfully.
Accessing It's Learning
Listing courses.
        Loading next page
        Loading next page
        Loading next page
        Item complete: this was the last page
Found 185 courses.
Listing projects.
Traceback (most recent call last):
  File "scrape.py", line 2069, in <module>
  File "scrape.py", line 1873, in list_courses_or_projects
  File "src\lxml\lxml.etree.pyx", line 1178, in lxml.etree._Element.__getitem__ (src\lxml\lxml.etree.c:54660)
IndexError: list index out of range
Failed to execute script scrape`

**Comment by bartvbl** [comment]
Seems to be a feature or some other oddity on the course list page of the NTNU It's Learning site. I can put in a check for this scenario, but that might also cause data not to be saved. Could you by chance show me a screenshot of your It's Learning course list?

To do so, go to It's Learning (NTNU), click on Courses -> All Courses, and select "All" from the dropdown box near the top. Make sure to blank out the course names (but not the table headers) because this page is publicly visible.

**Comment by bartvbl** [comment]
I believe I have fixed this issue recently. It had to do with the presence of project invitations. Please try again and open another issue if you still experience problems.
